package-lock.json, src/test/index.ts, src/test/outputchannel.log.test.ts, src/test/runTest.ts
=> added basic first test

.travis.yml, Jenkinsfile, package.json
=> re-enabled tests

Jenkinsfile
=> removed java deps. fixes #13

src/extension.ts, src/test/index.ts, src/test/outputchannel.log.test.ts, src/test/runTest.ts
=> added missing headers. fixes #8

package.json, src/extension.ts, src/model/tree/DVProjectTreeNode.ts, src/model/tree/DVTreeItem.ts, src/model/tree/DataSourceConfigEntryTreeNode.ts, src/model/tree/DataSourceTreeNode.ts, src/model/tree/DataSourcesTreeNode.ts, src/model/tree/SchemaTreeNode.ts, src/model/tree/SchemasTreeNode.ts, src/utils.ts
=> adding more commands

src/extension.ts
=> minor fix to the deletion of datasources which did not work for all entries

package-lock.json, package.json
it also avoids to play with different names in Jenkinsfile
=> Use same npm package name than the github repository #24

src/extension.ts, src/model/datasources/GoogleSheetsDataSource.ts, src/model/datasources/MongoDBDataSource.ts, src/model/datasources/RestBasedDataSource.ts, src/model/datasources/SalesForceDataSource.ts, src/model/datasources/SpringDataSource.ts, src/model/tree/DataSourceTreeNode.ts, src/model/tree/DataSourcesTreeNode.ts, src/utils.ts
=> added datasource types support

sonar-project.properties
=> Remove non-existent source folder from Sonar configuration #3

src/utils.ts
https://sonarcloud.io/project/issues?id=vscode-datavirt&issues=AXAfq8E9skCoWEIZoxJm&open=AXAfq8E9skCoWEIZoxJm
=> Remove unused import

src/model/tree/DataSourcesTreeNode.ts
https://sonarcloud.io/project/issues?id=vscode-datavirt&issues=AXAfq8DaskCoWEIZoxJl&open=AXAfq8DaskCoWEIZoxJl
=> Avoid shadowing variable name

package.json
=> Remove unused devDependencies #34

README.md
=> Redirect development related information to contributing.md #15

src/extension.ts
Signed-off-by: bfitzpat@redhat.com <bfitzpat@redhat.com>
=> adding check and error message for empty workspace on create vdb

package.json
=> Use https instead of http

Jenkinsfile
=> Use same indentation character (tabs) for the whole Jenkinsfile #12

package.json, src/utils.ts
=> fixed command naming #29

resources/vdb_template.yaml
=> vdb template should contain a ddl skeleton #60

src/extension.ts, src/model/tree/DataVirtNodeProvider.ts
I also included the change of the ddl file extension from .sql to .ddl as proposed by Barry.
=> auto open the ddl in editor after creation #30

package.json, src/commands/CreateDataSourceCommand.ts, src/commands/CreateDataSourceEntryCommand.ts, src/commands/CreateVDBCommand.ts, src/commands/DeleteDataSourceCommand.ts, src/commands/DeleteDataSourceEntryCommand.ts, src/commands/DeployVDBCommand.ts, src/commands/EditDataSourceEntryCommand.ts, src/commands/EditSchemaCommand.ts, src/commands/UndeployVDBCommand.ts, src/extension.ts, src/model/tree/SchemasTreeNode.ts, src/utils.ts
=> added validation to the VDB name #59

src/commands/CreateDataSourceCommand.ts, src/commands/EditDataSourceEntryCommand.ts, src/model/datasources/GoogleSheetsDataSource.ts, src/model/datasources/MongoDBDataSource.ts, src/model/datasources/RestBasedDataSource.ts, src/model/datasources/SalesForceDataSource.ts, src/model/datasources/SpringDataSource.ts
- wrong datasource entry key generation
- datasource entry names not generated uppercase
- wrong validation of the datasource entry value
=> fixed several smaller issues in commands

.gitignore, Changelog.md, jars/Readme.md, package-lock.json, package.json, scripts/postinstall.js, src/extension.ts, src/languageServer.ts, src/test/completion.ddl.test.ts
requires org.teiid:teiid-language-server to be available on Maven repository, see https://issues.redhat.com/browse/ENTESB-13172
=> ENTESB-13183 - use Teiid language server for ddl files

package-lock.json, package.json
=> bumped several dependency versions and fixed vulnerabilities

README.md, package.json
=> changed name of the extension #37

package.json
=> removed all commands which require a context from the palette #31

resources/vdb_template.yaml, src/commands/CreateVDBCommand.ts, src/extension.ts, src/test/commands.vdb.test.ts, src/test/utils.test.ts, src/utils.ts
=> ddl string placeholders for vdb name get injected now #85

package.json
=> fixed typo in the description of package.json - FUSETOOLS2-320

Changelog.md
=> FUSETOOLS2-341 - added current features to the Changelog

src/utils.ts
=> FUSETOOLS2-391 - removed log output for unimplemented function

Changelog.md
=> FUSETOOLS2-383 - improved wording in the change log

package.json, src/model/tree/DVProjectTreeNode.ts, src/model/tree/SchemaTreeNode.ts
=> FUSETOOLS2-399 - rename Schema to DDL

package.json
=> FUSETOOLS2-400 - renamed VDB create command to New Virtual Database

src/model/tree/DataVirtNodeProvider.ts, src/test/utils.test.ts, src/utils.ts
=> FUSETOOL2-385 - only processing files of kind VirtualDatabase

src/commands/CreateEnvironmentVariableCommand.ts, src/test/commands.environment.variables.test.ts, src/test/utils.test.ts, src/utils.ts
=> FUSETOOLS2-401 - added validation for environment variable names

package.json, src/commands/CreateVDBCommand.ts, src/commands/DeleteVDBCommand.ts, src/extension.ts, src/test/commands.vdb.test.ts, src/utils.ts
=> FUSETOOLS2-395 - added a Delete VDB command for the project tree node

src/model/tree/DataVirtNodeProvider.ts
=> fixed missing parameter for the treeevent fire method

scripts/postinstall.js, src/languageServer.ts, src/test/completion.ddl.test.ts
=> FUSETOOLS2-428 - added sql extension to supported file types for the lsp

src/utils.ts
=> FUSETOOLS2-455 - fixed validation messages to reflect the real regexp

Changelog.md, README.md
=> prepare initial release

src/commands/ConvertDataSourceCommand.ts
=> FUSETOOLS2-453 - removed typo duplication

Changelog.md, package-lock.json, package.json
=> prepare for next development iteration

Changelog.md, package-lock.json, package.json
=> prepare next development iteration 0.0.3
